# Use make -f Maefile.docker ... to run the relavant command

build:
	docker build --squash --tag hex0cter/openwrt-gl-ar300m-build-platform .

push:
	docker push hex0cter/openwrt-gl-ar300m-build-platform

pull:
	docker pull hex0cter/openwrt-gl-ar300m-build-platform

run:
	docker run -it --rm -v `pwd`:/usr/src/app --workdir /usr/src/app --name ar300 --entrypoint bash hex0cter/openwrt-gl-ar300m-build-platform
